# Toggle major subsystems on or off at launch time.
camera_enabled: false
pid_enabled: false
vesc_enabled: false
gps_enabled: true
search_enabled: false
mode_manager_enabled: false
cmd_mux_enabled: false
