tracker_camera_node:
  ros__parameters:
    fps_limit: 10
    lost_timeout_frames: 30
    target_box_fraction: 0.40
    model_path: ""
    tracker_cfg_path: ""
    enable_gui: true
    show_info_panel: true
    publish_annotated_image: true
    publish_debug_image: true
    publish_disparity_image: true
    enable_disparity: true
    extended_disparity: false
    subpixel: false
    lr_check: true
    image_frame_id: "camera_link"

tracker_pid_node:
  ros__parameters:
    Kp_steering: 0.8
    Ki_steering: 0.0
    Kd_steering: 0.10
    Kp_throttle: 0.5
    Ki_throttle: 0.0
    Kd_throttle: 0.05
    integral_max: 0.5
    max_speed: 0.50
    min_speed: 0.10
    max_steering: 1.0
    lateral_dead_band: 0.05
    distance_dead_band: 0.05
    Ts: 0.10
